style: improved setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -27,119 +27,188 @@ function error {
 # Print usage help
 ###
 function show_help {
-  echo "Usage: $0"
-  echo " -h         Show this help"
-  echo " -v         Verbose mode"
-  echo " -n         Do not run Ansible playbook"
-  echo " -q         Do not install Ansible requirements"
-  echo " -l         List available Ansible tags"
-  echo " -s         Ansible playbook syntax check"
-  echo " -t TAGS    Run Ansible with the given comma separated list of tags"
+    echo "Usage: $0"
+    echo " -h         Show this help"
+    echo " -v         Verbose mode"
+    echo " -n         Do not run Ansible playbook"
+    echo " -q         Do not install Ansible requirements"
+    echo " -l         List available Ansible tags"
+    echo " -s         Ansible playbook syntax check"
+    echo " -t TAGS    Run Ansible with the given comma separated list of tags"
 }
 
+###
+# Install dependencies on macOS
+###
+function install_macos_dependencies {
+    if [ "$install_homebrew" == "1" ]; then
+        if test ! $(which gcc); then
+            install_xcode_cli
+        fi
+        if test ! "$(which brew)"; then
+            install_homebrew
+        fi
+    fi
+    if [ "$install_ansible" == "1" ]; then
+        if test ! "$(which ansible)"; then
+            install_ansible_with_homebrew
+        fi
+    fi
+}
+
+###
+# Install Xcode Command Line Tools
+###
+function install_xcode_cli {
+    local errmsg="Failed to install Xcode Command Line Tools"
+    echo "*** Installing Xcode Command Line Tools..."
+    xcode-select --install \
+        || { error "${errmsg}"; exit 1; }
+}
+
+###
+# Install Homebrew
+###
+function install_homebrew {
+    local url="https://raw.githubusercontent.com"
+    url="${url}/Homebrew/install/master/install"
+    local errmsg="Failed to install Homebrew"
+    echo "*** Installing Homebrew..."
+    ruby -e "$(curl -fsSL ${url})" \
+        || { error "${errmsg}"; exit 1; }
+}
+
+###
+# Install Ansible with Homebrew
+###
+function install_ansible_with_homebrew {
+    local errmsg="Failed to install Ansible"
+    echo "*** Installing Ansible with Homebrew..."
+    brew install ansible \
+        || { error "${errmsg}"; exit 1; }
+}
+
+###
+# Install Ansible roles
+###
+function install_ansible_roles {
+    local errmsg="Failed to install Ansible roles"
+    echo "*** Installing Ansible roles..."
+    ansible-galaxy install -r requirements.yml -p ${ansible_roles} \
+        || { error "${errmsg}"; exit 1; }
+}
+
+###
+# Run Ansible playbook
+###
+function run_ansible_playbook {
+
+    local ansible_opts=""
+
+    if [ "$deploy_env" != "" ]; then
+        deploy_env_err="Could not find inventory file for ${deploy_env}"
+        [ -e "inventory/${deploy_env}" ] \
+            || { error "${deploy_env_err}"; exit 1; }
+        ansible_opts="-i inventory/${deploy_env} ${ansible_opts}"
+    fi
+
+    if [ "$ansible_verbose" == "1" ]; then
+        ansible_opts="-v ${ansible_opts}"
+    fi
+
+    if [ "$ansible_tags" != "" ]; then
+        ansible_opts="--tags=${ansible_tags} ${ansible_opts}"
+    fi
+
+    ansible-playbook ${ansible_playbook} $ansible_opts
+
+}
+
+###
+# Check Ansible playbook syntax
+###
+function check_ansible_playbook_syntax {
+    ansible-playbook ${ansible_playbook} --syntax-check
+}
+
+### 
+# List tags available in Ansible playbooks
+###
+function ansible_playbook_list_tags {
+    ansible-playbook ${ansible_playbook} --list-tags
+}
+
+###
+# Setup dependencies
+###
+function setup_dependencies {
+    if test "$(uname)" = "Darwin"; then
+        install_macos_dependencies
+    elif test "$(uname)" = "Linux"; then
+        error "Linux is not currently supported."
+        exit 1
+    fi
+    if test ! "$(which ansible)"; then
+        error "You system is not supported yet."
+        exit 1
+    fi
+    python --version
+    ansible --version
+}
+
+###
+# Parse command line options
+###
 while getopts ":hcnqlsvt:" opt; do
-  case $opt in
-    h)
-      show_help
-      exit 0
-      ;;
-    n)
-      run_playbook=0
-      ;;
-    q)
-      install_roles=0
-      install_ansible=0
-      install_homebrew=0
-      ;;
-    l)
-      list_tags=1
-      run_playbook=0
-      ;;
-    s)
-      syntax_check=1
-      run_playbook=0
-      ;;
-    v)
-      ansible_verbose=1
-      ;;
-    t)
-      ansible_tags=$OPTARG
-      ;;
-    \?)
-      error "Invalid option: -$OPTARG"
-      show_help
-      exit 1
-      ;;
-    :)
-      error "Option -$OPTARG requires an argument"
-      exit 1
-      ;;
-  esac
+    case $opt in
+        h)
+            show_help
+            exit 0
+            ;;
+        n)
+            run_playbook=0
+            ;;
+        q)
+            install_roles=0
+            install_ansible=0
+            install_homebrew=0
+            ;;
+        l)
+            list_tags=1
+            run_playbook=0
+            ;;
+        s)
+            syntax_check=1
+            run_playbook=0
+            ;;
+        v)
+            ansible_verbose=1
+            ;;
+        t)
+            ansible_tags=$OPTARG
+            ;;
+        \?)
+            error "Invalid option: -$OPTARG"
+            show_help
+            exit 1
+            ;;
+        :)
+            error "Option -$OPTARG requires an argument"
+            exit 1
+            ;;
+    esac
 done
 
-if test "$(uname)" = "Darwin"; then
-  if [ "$install_homebrew" == "1" ]; then
-    if test ! $(which gcc); then
-      echo "*** Installing Xcode Command Line Tools..."
-      xcode-select --install \
-        || { error "Failed to install Xcode Command Line Tools"; exit 1; }
-    fi
-    if test ! "$(which brew)"; then
-      echo "*** Installing Homebrew..."
-      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
-        || { error "Failed to install Homebrew"; exit 1; }
-    fi
-  fi
-  if [ "$install_ansible" == "1" ]; then
-    if test ! "$(which ansible)"; then
-      echo "*** Installing Ansible with Homebrew..."
-      brew install ansible \
-        || { error "Failed to install Ansible"; exit 1; }
-    fi
-  fi
-elif test "$(uname)" = "Linux"; then
-  error "Linux is not currently supported."
-  exit 1
-fi
-
-if test ! "$(which ansible)"; then
-  error "You system is not supported yet."
-  exit 1
-fi
-
-python --version
-ansible --version
+setup_dependencies
 
 if [ "$install_roles" == "1" ]; then
-  echo "*** Installing Ansible roles..."
-  ansible-galaxy install -r requirements.yml -p ${ansible_roles} || { error "Failed to install Ansible roles"; exit 1; }
+    install_ansible_roles
 fi
 
 if [ "$list_tags" == "1" ]; then
-
-  ansible-playbook ${ansible_playbook} --list-tags
-
+    ansible_playbook_list_tags
 elif [ "$syntax_check" == "1" ]; then
-
-  ansible-playbook ${ansible_playbook} --syntax-check
-
+    check_ansible_playbook_syntax
 elif [ "$run_playbook" == "1" ]; then
-
-  ansible_opts=""
-
-  if [ "$deploy_env" != "" ]; then
-    [ -e "inventory/${deploy_env}" ] || { error "Could not find inventory file for ${deploy_env}"; exit 1; }
-    ansible_opts="-i inventory/${deploy_env} ${ansible_opts}"
-  fi
-
-  if [ "$ansible_verbose" == "1" ]; then
-    ansible_opts="-v ${ansible_opts}"
-  fi
-
-  if [ "$ansible_tags" != "" ]; then
-    ansible_opts="--tags=${ansible_tags} ${ansible_opts}"
-  fi
-
-  ansible-playbook ${ansible_playbook} $ansible_opts
-
+    run_ansible_playbook
 fi
